<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RollForward>Major</RollForward>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <DebugType>portable</DebugType>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <NoWarn>NU1903</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.MTP" Version="10.1.0" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2" />
    <PackageReference Include="System.IO.Abstractions.TestingHelpers" Version="22.3.0" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="Moq" Version="4.21.0" />
    <PackageReference Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../GodotEnv/Chickensoft.GodotEnv.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="src\features\godot\domain\data\godot-4.3-dev5.json" />
    <EmbeddedResource Include="src\features\godot\domain\data\godot-4.3-dev5.json" />
    <None Remove="src\features\godot\domain\data\godot-1.1-stable.json" />
    <EmbeddedResource Include="src\features\godot\domain\data\godot-1.1-stable.json" />
  </ItemGroup>

</Project>
